version: '3.8'
services:
  go-gin-app:
    build: ./go/gin-app
    ports:
      - "3000:3000"
    networks:
      - backend

  node-express-app:
    build: ./node/express-app
    ports:
      - "3100:3100"
    networks:
      - backend

  fastify-app:
    build: ./node/fastify-app
    ports:
      - "3101:3101"
    networks:
      - backend

  python-django-app:
    build: ./python/django-app
    ports:
      - "3200:3200"
    networks:
      - backend

  tester:
    build: ./tester
    depends_on:
      - node-express-app
      - go-gin-app
      - python-django-app
    networks:
      - backend

networks:
  backend:
    driver: bridge
